### ISSUE TITLE
Typo Problem

### ISSUE THREAD

**Issue by AndersonZhangyq** [PaddlePaddle/PaddleClas#235]
In `dygraph` branch, I think that the module name `BisicBlock` should be `BasicBlock`.
It would be better if the module name is consistent with the name in origin paper ( and other frameworks ) to make it easier to understand.

**Comment by littletomatodonkey** [comment]
Thanks for your attention! The typo is fixed in #236

**Comment by AndersonZhangyq** [comment]
Great!

**Comment by AndersonZhangyq** [comment]
![image](https://user-images.githubusercontent.com/20550380/89251538-dd2ea600-d649-11ea-8096-7649147657a0.png)
It seems that some typos are still not fixed.

**Comment by littletomatodonkey** [comment]
All fixed in #237 , Thx!
